apiVersion: v1
kind: Namespace
metadata:
  name: tutorme

---
apiVersion: v1
kind: Secret
metadata:
  name: tutorme-secrets
  namespace: tutorme
type: Opaque
data:
  mongodb-url: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkQG1vbmdvOjI3MDE3L3R1dG9ybWU/YXV0aFNvdXJjZT1hZG1pbg==
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQtanN0LWtleS1oZXJl
  mongo-root-username: YWRtaW4=
  mongo-root-password: cGFzc3dvcmQ=

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: tutorme
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: tutorme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:7
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: tutorme-secrets
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tutorme-secrets
              key: mongo-root-password
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: tutorme
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tutorme-api
  namespace: tutorme
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tutorme-api
  template:
    metadata:
      labels:
        app: tutorme-api
    spec:
      containers:
      - name: tutorme-api
        image: tutorme-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: MONGODB_URL
          value: "mongodb://admin:password@mongo-service:27017/tutorme?authSource=admin"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: tutorme-secrets
              key: jwt-secret
        - name: JWT_ACCESS_EXPIRATION_MINUTES
          value: "30"
        - name: JWT_REFRESH_EXPIRATION_DAYS
          value: "30"
        - name: JWT_RESET_PASSWORD_EXPIRATION_MINUTES
          value: "10"
        - name: JWT_VERIFY_EMAIL_EXPIRATION_MINUTES
          value: "10"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: tutorme-api-service
  namespace: tutorme
spec:
  selector:
    app: tutorme-api
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
